import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faGlobeAmericas,
  faUserPlus,
  faUserCheck,
  faPlus,
  faSearch,
  faPaperPlane,
  faShare,
  faTimes,
  faUserFriends,
  faLock,
  faEllipsisV,
  faEllipsisH,
  faPlay,
  faPause,
  faGlobe,
  faMinus,
  faCog,
  faBell as fasBell,
  faInfoCircle,
  faBars,
  faSmile as fasSmile,
  faUsers,
  faRedoAlt,
  faTv,
  faImage,
  faHeart,
  faVolumeUp,
  faVolumeMute,
  faCompress,
  faCheck,
  faArrowLeft
} from "@fortawesome/free-solid-svg-icons";
import {
  faSmile as farSmile,
  faImages as farImages,
  faBell as farBell,
  faHeart as farHeart,
  faComment as farComment
} from "@fortawesome/free-regular-svg-icons";
// import { fab } from "@fortawesome/free-brands-svg-icons";

library.add(
  faGlobeAmericas,
  faUserPlus,
  faGlobe,
  faUserCheck,
  faPlus,
  faMinus,
  faSearch,
  faTv,
  faPaperPlane,
  faShare,
  faTimes,
  faUserFriends,
  faLock,
  faEllipsisV,
  faEllipsisH,
  faPlay,
  faPause,
  faCog,
  fasBell,
  farBell,
  faInfoCircle,
  faBars,
  fasSmile,
  farSmile,
  farImages,
  faImage,
  faUsers,
  faRedoAlt,
  farHeart,
  farComment,
  faHeart,
  faVolumeUp,
  faVolumeMute,
  faCompress,
  faCheck,
  faArrowLeft
);
